const GET_KEYS = 'GET_KEYS'
const GET_KEY_HISTORY = 'GET_HISTORY'
const CLEAR_NODE_DATA = "CLEAR_NODE_DATA"
const CLEAR_DATA = "CLEAR_DATA"
const SORT_BY_TYPE = "SORT_BY_TYPE"
const SORT_BY_DATE = "SORT_BY_DATE"
const CHANGE_STATUS = "CHANGE_STATUS"

export default {
    GET_KEYS,//
    GET_KEY_HISTORY,//
    CLEAR_NODE_DATA,//
    CLEAR_DATA,
    SORT_BY_DATE,
    SORT_BY_TYPE,
    CHANGE_STATUS
}
